#!/bin/bash

docker run -d --name adup-cronsmbload \
  -v /home/sv/src/adup_cfg/adup.conf:/opt/adup/adup.conf:ro \
  -v adup_tmp:/opt/adup/tmp \
  -e TZ=Asia/Yekaterinburg \
  -u root:root \
  --init \
  uralm1/adup crond -f -M /bin/true -l 8
