#!/bin/bash

#docker volume create adup_tmp
docker run -d --name adup-cron \
  -v /srv/adup/adup.conf:/opt/adup/adup.conf:ro \
  -v adup_tmp:/opt/adup/tmp \
  -e TZ=Asia/Yekaterinburg \
  uralm1/adup sh -c "script/check_db_hosts && script/adup cron -m production"
