version: "3.7"
services:
  proxy:
    image: uralm1/uwc-llng-proxy
    container_name: adup-proxy
    hostname: adup
    domainname: uwc.ufanet.ru
    networks:
      uwcnet:
        ipv4_address: 10.14.72.3
      default:
    dns:
      - 10.14.0.2
      - 10.14.0.4
    volumes:
      - /etc/ssl/certs/uwc.ufanet.ru.pem:/etc/ssl/certs/u.pem:ro
      - /etc/ssl/private/uwc.ufanet.ru-key.pem:/etc/ssl/private/u.key:ro
      - public:/opt/adup/public
    environment:
      - TZ=Asia/Yekaterinburg
      - PUBLIC_ROOT=/opt/adup/public
      - PROXY_ADDR=http://adup-app:3000/
    links:
      - app:adup-app
    restart: unless-stopped

  app:
    image: uralm1/adup
    container_name: adup
    volumes:
      - /srv/adup/adup.conf:/opt/adup/adup.conf:ro
      - tmp:/opt/adup/tmp
      - public:/opt/adup/public
    environment:
      - TZ=Asia/Yekaterinburg
    links:
      - worker
    restart: unless-stopped

  worker:
    image: uralm1/adup
    container_name: adup-minion
    volumes:
      - /srv/adup/adup.conf:/opt/adup/adup.conf:ro
      - tmp:/opt/adup/tmp
    environment:
      - TZ=Asia/Yekaterinburg
    stop_signal: SIGINT
    command: sh -c "script/check_db_hosts && script/adup minion worker -m production -j 1"
    restart: unless-stopped

  cron:
    image: uralm1/adup
    container_name: adup-cron
    volumes:
      - /srv/adup/adup.conf:/opt/adup/adup.conf:ro
      - tmp:/opt/adup/tmp
    environment:
      - TZ=Asia/Yekaterinburg
    command: sh -c "script/check_db_hosts && script/adup cron -m production"
    links:
      - worker
    restart: unless-stopped

volumes:
  tmp:
  public:

networks:
  uwcnet:
    external:
      name: uwcnet

