#!/usr/bin/env perl

use strict;
use warnings;

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

Mojolicious::Commands->start_app('Adup', 'prefork', '-l', 'http://*:3000', '-p', '-P', '/opt/adup/run/prefork.pid');
